subscribers:
  imu_topic: "/wamv/sensors/imu/imu/data"
  gps_topic: "/wamv/sensors/gps/gps/fix"
  # imu_topic: "/vectornav/imu_uncompensated"
  # gps_topic: "/navsatfix"

  translation_gps_source_to_body: [0, 0, 0]
  rotation_gps_source_to_body: [1, 0, 0, 0]

publishers:
  pose_publish_rate: 100  # Hz
  pose_publish_topic: "/drift/pose"
  pose_frame: "map"
  base_link_frame: "wamv/base_link"

  path_publish_rate: 10   # Hz
  path_publish_topic: "/drift/path"

  twist_publish_topic: "/drift/twist"

